//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMICard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMICard()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Card_Number { get; set; }
        public string username { get; set; }
        public Nullable<bool> Card_Type { get; set; }
        public System.DateTime valid { get; set; }
        public bool Active { get; set; }
        public string admin_username { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Card Card { get; set; }
        public virtual RegisterBank RegisterBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
