//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbfinanceEntities : DbContext
    {
        public dbfinanceEntities()
            : base("name=dbfinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<EMICard> EMICards { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RegisterBank> RegisterBanks { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    }
}
