//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class RegisterBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterBank()
        {
            this.EMICards = new HashSet<EMICard>();
        }
    
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string email { get; set; }
        [DataMember]
        public string Phone_No { get; set; }
        [DataMember]
        public string username { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string Address { get; set; }
        [DataMember]
        public bool Card_Type { get; set; }
        [DataMember]
        public Nullable<bool> Fees_Paid { get; set; }
        [DataMember]
        public string Bank_Name { get; set; }
        [DataMember]
        public int Account_Number { get; set; }
        [DataMember]
        public string IFSC_Code { get; set; }
        [DataMember]
        public string document { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMICard> EMICards { get; set; }
    }
}
